#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stopMoving();
void forwards();
void backwards();
void left();
void right();
void open();
void close();

task main()
{
	right();
	open();
	forwards();
	wait1Msec(900);
	stopMoving();
	close();
	wait1Msec(500);
	backwards();
	wait1Msec(900);
	stopMoving();
	wait1Msec(500);
	left();
	motor[arm] = -50;
	wait1Msec(1000);
	motor[arm] = 0;
	forwards();
	wait1Msec(3300);
	stopMoving();
	open();
	wait1Msec(500);
	close();
	backwards();
	wait1Msec(1000);
	motor[arm] = 50;
	wait1Msec(500);
	motor[arm] = 0;
	wait1Msec(800);
	stopMoving();
	left();
	open();
	forwards();
	wait1Msec(900);
	stopMoving();
	close();
	backwards();
	wait1Msec(1100);
	stopMoving();
	right();
	wait1Msec(500);
	motor[arm] = -50;
	wait1Msec(500);
	motor[arm] = 0;
	forwards();
	wait1Msec(3000);
	stopMoving();
	open();
	
}

void forwards() {
	motor[leftMotor] = -57;
	motor[rightMotor] = -50;
}

void backwards() {
	motor[leftMotor] = 57;
	motor[rightMotor] = 50;
}

void stopMoving() {
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

void right() {
	motor[leftMotor] = -50;
	motor[rightMotor] = 50;
	wait1Msec(810);
	stopMoving();
}

void left() {
	motor[leftMotor] = 60;
	motor[rightMotor] = -50;
	wait1Msec(740);
	stopMoving();
}

void open() {
	motor[claw] = 50;
	wait1Msec(700);
	motor[claw] = 0;
}

void close() {
	motor[claw] = -50;
	wait1Msec(700);
	motor[claw] = 0;
}
